/control:
  gazebo_ros_control:   
    pid_gains:
      arm1_propeller1: {p: 100.0, i: 0.1, d: 10.0}
      arm3_propeller3: {p: 100.0, i: 0.1, d: 10.0}
      arm4_propeller4: {p: 100.0, i: 0.1, d: 10.0}
      arm6_propeller6: {p: 100.0, i: 0.1, d: 10.0}
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 10

    joint_motor_controller:
      type: velocity_controllers/JointGroupVelocityController
      joints:
        - arm1_propeller1
        - arm3_propeller3
        - arm4_propeller4
        - arm6_propeller6
  joint_velocity_controller:
    type: velocity_controllers/JointGroupVelocityController
    joints:
      - arm1_propeller1
      - arm3_propeller3
      - arm4_propeller4
      - arm6_propeller6
