joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

propeller1_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm1_propeller1
  pid: {p: 100.0, i: 0.01, d: 0.01, i_clamp: 1.0}

propeller3_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm3_propeller3
  pid: {p: 100.0, i: 0.01, d: 0.01, i_clamp: 1.0}

propeller4_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm4_propeller4
  pid: {p: 100.0, i: 0.01, d: 0.01, i_clamp: 1.0}

propeller6_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm6_propeller6
  pid: {p: 100.0, i: 0.01, d: 0.01, i_clamp: 1.0}
